navbar:
  blog_title: 醉里博客
  ground_glass:
    enable: true
index:
  banner_img: /images/uploads/bbc58c3d998d4f389fdae649334873f7.jpg
  banner_img_height: 100
  slogan:
    text: 醉里挑灯看剑，梦回吹角连营。
post:
  banner_img: /images/uploads/1616421416500-wallhaven-rddv31.jpg
  banner_img_height: 70
  default_index_img: /images/uploads/default_post_img.png
archive:
  banner_img: /images/uploads/1616421416500-wallhaven-rddv31.jpg
  banner_img_height: 80
  subtitle: null
category:
  banner_img: /images/uploads/1616421416500-wallhaven-rddv31.jpg
  banner_img_height: 80
  subtitle: null
tag:
  banner_img: /images/uploads/1616421669417-wallhaven-1kkm2g.jpg
  banner_img_height: 80
  subtitle: null
about:
  banner_img: /images/uploads/wallhaven-pkkr2.webp
  banner_img_height: 80
  subtitle: null
  avatar: /images/uploads/yutzi.jpg
  name: 醉里
  intro: My blog
links:
  banner_img: /images/uploads/1616421416500-wallhaven-rddv31.jpg
  banner_img_height: 80
  subtitle: null
  items:
    - title: 小理の小窝
      intro: 一个普通学生的普通生活
      link: https://xiaolii.com/
      avatar: https://502.chat/Imagesource/icon.jpg
